### ISSUE TITLE
A few mod suggestions

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica4#116]
* [Silent's Gems](https://www.curseforge.com/minecraft/mc-mods/silents-gems) The classic lesser-known alternative to Tinkers is now mostly just the gems
* [Silent Gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear) The gear is now in a separate mod that works with or without Silent Gems
* [Druid Craft](https://www.curseforge.com/minecraft/mc-mods/druidcraft)This is more of a investigate rather than please add. It has much potential and adds some interesting stuff. Still has enough neat stuff to warrant adding if that's on the table. The dev is new and has ambitious plans so there might be more than your average number of issues but I intend to check it out. 
* [Thermal Solars](https://www.curseforge.com/minecraft/mc-mods/thermal-solars) Adds some much needed additional ways to generate RF

**Comment by NielsPilgaard** [comment]
I've tried out Silent's Gear, but I couldn't shake the feeling that it was messy, because of the shear amount of materials. I should probably revisit it, but for some reason I can't really motivate myself to do it ^^'

DruidCraft is definitely on my radar, haven't played with it yet though. I'll love to hear your take on it once you've had a look.

Thermal Solars I agree on - We'll probably need to adjust the recipes sooner or later though.

**Comment by Halfdeaf** [comment]
Totally agree, recipe tweaks definitely needed. 

I haven't really played with Silent gems in a long time and they did rework the entire system. I can take a look and give you a condensed summary once a form an opinion

**Comment by NielsPilgaard** [comment]
That'd be really nice :)
Note to self: Investigate if Thermal Solars has an off-config for tools and ores.
