### ISSUE TITLE
Add Botania

### ISSUE THREAD

**Issue by axieum** [NillerMedDild/Enigmatica4#221]
https://www.curseforge.com/minecraft/mc-mods/botania

**Comment by axieum** [comment]
Just thought I'd post this here, in case you miss it, as it got released today.

**Comment by NielsPilgaard** [comment]
Thanks!

**Comment by geoffmca** [comment]
This seems to be causing an issue on the server side. I believe it it due to this -> https://github.com/Vazkii/Botania/pull/3068

From the server logs there are multiple examples like this:

[05:43:58] [Server thread/ERROR] [minecraft/LootTableManager]: Couldn't parse loot table minecraft:chests/abandoned_mineshaft
,java.lang.NullPointerException: null

Removing Botania from the server mod folder and client address the issue for the interim (I also tried to rebuild the server from scratch and had the same result). Basically trying to make you aware that we will need this fixed version once it makes it into the releases.

**Comment by NielsPilgaard** [comment]
Which error does it cause?

**Comment by Frikkle** [comment]
The referenced PR mentions it closes issue https://github.com/Vazkii/Botania/issues/3066

**Comment by geoffmca** [comment]
it stops the server from fully loading and clients cant connect. The next botanica build should fix the issue. The error above is repeated 5 or 6 times. I am assuming a new build should happen in the near term. Mainly trying to call this out as it took me 2 hours to track down last night.

**Comment by NielsPilgaard** [comment]
Thanks a lot for the info :)

**Comment by Darkere** [comment]
@gorf18 I'm able to connect to a server running the newest version of the pack just fine. While a few other things are very much broken, none should impact playability too much.
