### ISSUE TITLE
Crash on Exit 

### ISSUE THREAD

**Issue by XxPowerEyexX** [NillerMedDild/Enigmatica4#299]
**Modpack version**
0.4.8

**Issue**
Pack Crashes on save and exit. shows the title screen briefly and then crashes to launcher.

**Logs**
https://pastebin.com/NasJg51A

**Comment by NielsPilgaard** [comment]
This is a known issue, but thank you for reporting it :)

**Comment by NielsPilgaard** [comment]
You had the world Open to LAN right?

the issue has been reported here for reference: https://github.com/KubeJS-Mods/KubeJS/issues/7

**Comment by XxPowerEyexX** [comment]
that's a negative ghost rider. single player as well as on lan

**Comment by NielsPilgaard** [comment]
Ah dammit, I'll look into it again then, thanks!

**Comment by NielsPilgaard** [comment]
I can no longer reproduce it, so I think it's fixed - Please let me know if version 0.4.9 doesn't fix it for you :)

It should be available within 24 hours, but no promises.

**Comment by XxPowerEyexX** [comment]
thank you

**Comment by XxPowerEyexX** [comment]
i updated to the beta and on the beta at least im still crashing 

PasteBin is here https://pastebin.com/VCzgNfuR

<blockquote><div><strong><a href="https://pastebin.com/VCzgNfuR">Pastebin.com - Access Denied Warning</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

<blockquote><div><strong><a href="https://www.java.com/en/download/manual.jsp">Java Downloads for All Operating Systems</a></strong></div><div>Java manual download page. Get the latest version of the Java Runtime Environment (JRE) for Windows, Mac, Solaris, and Linux.</div></blockquote>
