### ISSUE TITLE
Clumps Mod

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#50]
I suspect it could be a part of a hanging world issue.

**Comment by axieum** [comment]
Tried to install Clumps on our server, and some thread just hangs, some stuff works. The ping shows up as `???` in the server listing.

This mod is a must have, since the only method of EXP storage is Experience Bottles from a Item Router (Modular Routers - XP Vacuum Module). Having one of those as well, auto clicking them for fastest EXP transfer causes lag with the amount of orbs orbiting the player - even with a experience necklace thing...

Any update on this?

**Comment by NielsPilgaard** [comment]
Check out the global xp mod.

**Comment by axieum** [comment]
Hmm, but this is storing already collected levels? I'm talking about storing the EXP from a mob farm.

Current setup is an **Item Router** (from Modular Routers) with a **Vacuum Module** equipped with an **XP Vacuum Augment**. As there is no _Liquid XP_ in this modpack, its only option is to provide **XP Bottle**s. I can't find any other way to collect the XP from these bottles, unless I setup an **Item Router** with a **Player Module** and speed upgrades to splash them on my fast enough. Which causes severe server lag due to the amount of experience orb entities. Perhaps this XP block you talk about will let me insert bottles into it?

I'll report back if this mod can solve this.

**Comment by Darkere** [comment]
You can avoid the lag by using the ring of attraction. It immediately picks up all xp.

**Comment by axieum** [comment]
This. This is perfect, thanks @Darkere!
